### ISSUE TITLE
The Lower third is removing itself instanley when clicking hide instead of moving slowly out

### ISSUE THREAD

**Issue by jccroft1** [joshhodgson/la1tv-graphics#6]

**Comment by joshhodgson** [comment]
Can't recreate. can you provide step by step instructions to recreate the issue?

**Comment by jccroft1** [comment]
switch it all on and then with the live, clock, and logo, when showing the lower 3rd the box comes in gittery and when hiding it starts to move out smoothly bit then disappears before it disappears nicely

**Comment by joshhodgson** [comment]
can only recreate when double clicking "show"

**Comment by joshhodgson** [comment]
Resolved. User error ( @benjaminkay93 )
